# Generated by Django 4.1.6 on 2023-02-24 17:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_is_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribed_to',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
