# Generated by Django 4.1.6 on 2023-02-24 17:54

import builtins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_subscribed_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscribed_to',
            field=models.ManyToManyField(limit_choices_to={'id__ne': builtins.id}, to=settings.AUTH_USER_MODEL),
        ),
    ]
