# Generated by Django 4.1.6 on 2023-02-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_subscribed_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscribed_to',
        ),
    ]
