# Generated by Django 4.1.6 on 2023-02-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_user_subscribed_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='images/male.png', upload_to='user_profile/'),
        ),
    ]
