# Generated by Django 4.1.6 on 2023-02-24 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-created_at']},
        ),
    ]
