# Generated by Django 4.1.6 on 2023-02-25 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscribers',
            field=models.ManyToManyField(default=None, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
